
CREATE TABLE IF NOT EXISTS "tin"."access_level" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "access_level_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "access_level_id_idx" ON "tin"."access_level" USING btree ("id");
COMMENT ON TABLE "tin"."access_level" IS 'Уровень доступа к счёту.';
COMMENT ON COLUMN "tin"."access_level"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."access_level"."name" IS 'Наименование';
INSERT INTO "access_level"(id, name) VALUES
(0, 'ACCOUNT_ACCESS_LEVEL_UNSPECIFIED'),
(1, 'ACCOUNT_ACCESS_LEVEL_FULL_ACCESS'),
(2, 'ACCOUNT_ACCESS_LEVEL_READ_ONLY'),
(3, 'ACCOUNT_ACCESS_LEVEL_NO_ACCESS');


CREATE TABLE IF NOT EXISTS "tin"."account_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "account_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "account_status_id_idx" ON "tin"."account_status" USING btree ("id");
COMMENT ON TABLE "tin"."account_status" IS 'Статус счёта.';
COMMENT ON COLUMN "tin"."account_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."account_status"."name" IS 'Наименование';
INSERT INTO "account_status"(id, name) VALUES
(0, 'ACCOUNT_STATUS_UNSPECIFIED'),
(1, 'ACCOUNT_STATUS_NEW'),
(2, 'ACCOUNT_STATUS_OPEN'),
(3, 'ACCOUNT_STATUS_CLOSED');


CREATE TABLE IF NOT EXISTS "tin"."account_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "account_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "account_type_id_idx" ON "tin"."account_type" USING btree ("id");
COMMENT ON TABLE "tin"."account_type" IS 'Тип счёта.';
COMMENT ON COLUMN "tin"."account_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."account_type"."name" IS 'Наименование';
INSERT INTO "account_type"(id, name) VALUES
(0, 'ACCOUNT_TYPE_UNSPECIFIED'),
(1, 'ACCOUNT_TYPE_TINKOFF'),
(2, 'ACCOUNT_TYPE_TINKOFF_IIS'),
(3, 'ACCOUNT_TYPE_INVEST_BOX');


CREATE TABLE IF NOT EXISTS "tin"."asset_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "asset_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "asset_type_id_idx" ON "tin"."asset_type" USING btree ("id");
COMMENT ON TABLE "tin"."asset_type" IS 'Тип актива.';
COMMENT ON COLUMN "tin"."asset_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."asset_type"."name" IS 'Наименование';
INSERT INTO "asset_type"(id, name) VALUES
(0, 'ASSET_TYPE_UNSPECIFIED'),
(1, 'ASSET_TYPE_CURRENCY'),
(2, 'ASSET_TYPE_COMMODITY'),
(3, 'ASSET_TYPE_INDEX'),
(4, 'ASSET_TYPE_SECURITY');


CREATE TABLE IF NOT EXISTS "tin"."candle_interval" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "candle_interval_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "candle_interval_id_idx" ON "tin"."candle_interval" USING btree ("id");
COMMENT ON TABLE "tin"."candle_interval" IS 'Интервал свечей.';
COMMENT ON COLUMN "tin"."candle_interval"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."candle_interval"."name" IS 'Наименование';
INSERT INTO "candle_interval"(id, name) VALUES
(0, 'CANDLE_INTERVAL_UNSPECIFIED'),
(1, 'CANDLE_INTERVAL_1_MIN'),
(2, 'CANDLE_INTERVAL_5_MIN'),
(3, 'CANDLE_INTERVAL_15_MIN'),
(4, 'CANDLE_INTERVAL_HOUR'),
(5, 'CANDLE_INTERVAL_DAY'),
(6, 'CANDLE_INTERVAL_2_MIN'),
(7, 'CANDLE_INTERVAL_3_MIN'),
(8, 'CANDLE_INTERVAL_10_MIN'),
(9, 'CANDLE_INTERVAL_30_MIN'),
(10, 'CANDLE_INTERVAL_2_HOUR'),
(11, 'CANDLE_INTERVAL_4_HOUR'),
(12, 'CANDLE_INTERVAL_WEEK'),
(13, 'CANDLE_INTERVAL_MONTH');


CREATE TABLE IF NOT EXISTS "tin"."coupon_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "coupon_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "coupon_type_id_idx" ON "tin"."coupon_type" USING btree ("id");
COMMENT ON TABLE "tin"."coupon_type" IS 'Тип купонов.';
COMMENT ON COLUMN "tin"."coupon_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."coupon_type"."name" IS 'Наименование';
INSERT INTO "coupon_type"(id, name) VALUES
(0, 'COUPON_TYPE_UNSPECIFIED'),
(1, 'COUPON_TYPE_CONSTANT'),
(2, 'COUPON_TYPE_FLOATING'),
(3, 'COUPON_TYPE_DISCOUNT'),
(4, 'COUPON_TYPE_MORTGAGE'),
(5, 'COUPON_TYPE_FIX'),
(6, 'COUPON_TYPE_VARIABLE'),
(7, 'COUPON_TYPE_OTHER');


CREATE TABLE IF NOT EXISTS "tin"."currency_request" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "currency_request_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "currency_request_id_idx" ON "tin"."currency_request" USING btree ("id");
COMMENT ON TABLE "tin"."currency_request" IS '';
COMMENT ON COLUMN "tin"."currency_request"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."currency_request"."name" IS 'Наименование';
INSERT INTO "currency_request"(id, name) VALUES
(0, 'RUB'),
(1, 'USD'),
(2, 'EUR');


CREATE TABLE IF NOT EXISTS "tin"."edit_favorites_action_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "edit_favorites_action_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "edit_favorites_action_type_id_idx" ON "tin"."edit_favorites_action_type" USING btree ("id");
COMMENT ON TABLE "tin"."edit_favorites_action_type" IS 'Тип действия со списком избранных инструментов.';
COMMENT ON COLUMN "tin"."edit_favorites_action_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."edit_favorites_action_type"."name" IS 'Наименование';
INSERT INTO "edit_favorites_action_type"(id, name) VALUES
(0, 'EDIT_FAVORITES_ACTION_TYPE_UNSPECIFIED'),
(1, 'EDIT_FAVORITES_ACTION_TYPE_ADD'),
(2, 'EDIT_FAVORITES_ACTION_TYPE_DEL');


CREATE TABLE IF NOT EXISTS "tin"."instrument_id_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "instrument_id_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "instrument_id_type_id_idx" ON "tin"."instrument_id_type" USING btree ("id");
COMMENT ON TABLE "tin"."instrument_id_type" IS 'Тип идентификатора инструмента. Подробнее об идентификации инструментов: [Идентификация инструментов](https://tinkoff.github.io/investAPI/faq_identification/)';
COMMENT ON COLUMN "tin"."instrument_id_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."instrument_id_type"."name" IS 'Наименование';
INSERT INTO "instrument_id_type"(id, name) VALUES
(0, 'INSTRUMENT_ID_UNSPECIFIED'),
(1, 'INSTRUMENT_ID_TYPE_FIGI'),
(2, 'INSTRUMENT_ID_TYPE_TICKER'),
(3, 'INSTRUMENT_ID_TYPE_UID'),
(4, 'INSTRUMENT_ID_TYPE_POSITION_UID');


CREATE TABLE IF NOT EXISTS "tin"."instrument_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "instrument_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "instrument_status_id_idx" ON "tin"."instrument_status" USING btree ("id");
COMMENT ON TABLE "tin"."instrument_status" IS 'Статус запрашиваемых инструментов.';
COMMENT ON COLUMN "tin"."instrument_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."instrument_status"."name" IS 'Наименование';
INSERT INTO "instrument_status"(id, name) VALUES
(0, 'INSTRUMENT_STATUS_UNSPECIFIED'),
(1, 'INSTRUMENT_STATUS_BASE'),
(2, 'INSTRUMENT_STATUS_ALL');


CREATE TABLE IF NOT EXISTS "tin"."instrument_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "instrument_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "instrument_type_id_idx" ON "tin"."instrument_type" USING btree ("id");
COMMENT ON TABLE "tin"."instrument_type" IS 'Тип инструмента.';
COMMENT ON COLUMN "tin"."instrument_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."instrument_type"."name" IS 'Наименование';
INSERT INTO "instrument_type"(id, name) VALUES
(0, 'INSTRUMENT_TYPE_UNSPECIFIED'),
(1, 'INSTRUMENT_TYPE_BOND'),
(2, 'INSTRUMENT_TYPE_SHARE'),
(3, 'INSTRUMENT_TYPE_CURRENCY'),
(4, 'INSTRUMENT_TYPE_ETF'),
(5, 'INSTRUMENT_TYPE_FUTURES'),
(6, 'INSTRUMENT_TYPE_SP'),
(7, 'INSTRUMENT_TYPE_OPTION'),
(8, 'INSTRUMENT_TYPE_CLEARING_CERTIFICATE');


CREATE TABLE IF NOT EXISTS "tin"."operation_state" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "operation_state_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "operation_state_id_idx" ON "tin"."operation_state" USING btree ("id");
COMMENT ON TABLE "tin"."operation_state" IS 'Статус запрашиваемых операций.';
COMMENT ON COLUMN "tin"."operation_state"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."operation_state"."name" IS 'Наименование';
INSERT INTO "operation_state"(id, name) VALUES
(0, 'OPERATION_STATE_UNSPECIFIED'),
(1, 'OPERATION_STATE_EXECUTED'),
(2, 'OPERATION_STATE_CANCELED'),
(3, 'OPERATION_STATE_PROGRESS');


CREATE TABLE IF NOT EXISTS "tin"."operation_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "operation_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "operation_type_id_idx" ON "tin"."operation_type" USING btree ("id");
COMMENT ON TABLE "tin"."operation_type" IS 'Тип операции.';
COMMENT ON COLUMN "tin"."operation_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."operation_type"."name" IS 'Наименование';
INSERT INTO "operation_type"(id, name) VALUES
(0, 'OPERATION_TYPE_UNSPECIFIED'),
(1, 'OPERATION_TYPE_INPUT'),
(2, 'OPERATION_TYPE_BOND_TAX'),
(3, 'OPERATION_TYPE_OUTPUT_SECURITIES'),
(4, 'OPERATION_TYPE_OVERNIGHT'),
(5, 'OPERATION_TYPE_TAX'),
(6, 'OPERATION_TYPE_BOND_REPAYMENT_FULL'),
(7, 'OPERATION_TYPE_SELL_CARD'),
(8, 'OPERATION_TYPE_DIVIDEND_TAX'),
(9, 'OPERATION_TYPE_OUTPUT'),
(10, 'OPERATION_TYPE_BOND_REPAYMENT'),
(11, 'OPERATION_TYPE_TAX_CORRECTION'),
(12, 'OPERATION_TYPE_SERVICE_FEE'),
(13, 'OPERATION_TYPE_BENEFIT_TAX'),
(14, 'OPERATION_TYPE_MARGIN_FEE'),
(15, 'OPERATION_TYPE_BUY'),
(16, 'OPERATION_TYPE_BUY_CARD'),
(17, 'OPERATION_TYPE_INPUT_SECURITIES'),
(18, 'OPERATION_TYPE_SELL_MARGIN'),
(19, 'OPERATION_TYPE_BROKER_FEE'),
(20, 'OPERATION_TYPE_BUY_MARGIN'),
(21, 'OPERATION_TYPE_DIVIDEND'),
(22, 'OPERATION_TYPE_SELL'),
(23, 'OPERATION_TYPE_COUPON'),
(24, 'OPERATION_TYPE_SUCCESS_FEE'),
(25, 'OPERATION_TYPE_DIVIDEND_TRANSFER'),
(26, 'OPERATION_TYPE_ACCRUING_VARMARGIN'),
(27, 'OPERATION_TYPE_WRITING_OFF_VARMARGIN'),
(28, 'OPERATION_TYPE_DELIVERY_BUY'),
(29, 'OPERATION_TYPE_DELIVERY_SELL'),
(30, 'OPERATION_TYPE_TRACK_MFEE'),
(31, 'OPERATION_TYPE_TRACK_PFEE'),
(32, 'OPERATION_TYPE_TAX_PROGRESSIVE'),
(33, 'OPERATION_TYPE_BOND_TAX_PROGRESSIVE'),
(34, 'OPERATION_TYPE_DIVIDEND_TAX_PROGRESSIVE'),
(35, 'OPERATION_TYPE_BENEFIT_TAX_PROGRESSIVE'),
(36, 'OPERATION_TYPE_TAX_CORRECTION_PROGRESSIVE'),
(37, 'OPERATION_TYPE_TAX_REPO_PROGRESSIVE'),
(38, 'OPERATION_TYPE_TAX_REPO'),
(39, 'OPERATION_TYPE_TAX_REPO_HOLD'),
(40, 'OPERATION_TYPE_TAX_REPO_REFUND'),
(41, 'OPERATION_TYPE_TAX_REPO_HOLD_PROGRESSIVE'),
(42, 'OPERATION_TYPE_TAX_REPO_REFUND_PROGRESSIVE'),
(43, 'OPERATION_TYPE_DIV_EXT'),
(44, 'OPERATION_TYPE_TAX_CORRECTION_COUPON'),
(45, 'OPERATION_TYPE_CASH_FEE'),
(46, 'OPERATION_TYPE_OUT_FEE'),
(47, 'OPERATION_TYPE_OUT_STAMP_DUTY'),
(50, 'OPERATION_TYPE_OUTPUT_SWIFT'),
(51, 'OPERATION_TYPE_INPUT_SWIFT'),
(53, 'OPERATION_TYPE_OUTPUT_ACQUIRING'),
(54, 'OPERATION_TYPE_INPUT_ACQUIRING'),
(55, 'OPERATION_TYPE_OUTPUT_PENALTY'),
(56, 'OPERATION_TYPE_ADVICE_FEE'),
(57, 'OPERATION_TYPE_TRANS_IIS_BS'),
(58, 'OPERATION_TYPE_TRANS_BS_BS'),
(59, 'OPERATION_TYPE_OUT_MULTI'),
(60, 'OPERATION_TYPE_INP_MULTI'),
(61, 'OPERATION_TYPE_OVER_PLACEMENT'),
(62, 'OPERATION_TYPE_OVER_COM'),
(63, 'OPERATION_TYPE_OVER_INCOME'),
(64, 'OPERATION_TYPE_OPTION_EXPIRATION');


CREATE TABLE IF NOT EXISTS "tin"."option_direction" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "option_direction_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "option_direction_id_idx" ON "tin"."option_direction" USING btree ("id");
COMMENT ON TABLE "tin"."option_direction" IS 'Тип опциона по направлению сделки.';
COMMENT ON COLUMN "tin"."option_direction"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."option_direction"."name" IS 'Наименование';
INSERT INTO "option_direction"(id, name) VALUES
(0, 'OPTION_DIRECTION_UNSPECIFIED'),
(1, 'OPTION_DIRECTION_PUT'),
(2, 'OPTION_DIRECTION_CALL');


CREATE TABLE IF NOT EXISTS "tin"."option_payment_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "option_payment_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "option_payment_type_id_idx" ON "tin"."option_payment_type" USING btree ("id");
COMMENT ON TABLE "tin"."option_payment_type" IS 'Тип расчетов по опциону.';
COMMENT ON COLUMN "tin"."option_payment_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."option_payment_type"."name" IS 'Наименование';
INSERT INTO "option_payment_type"(id, name) VALUES
(0, 'OPTION_PAYMENT_TYPE_UNSPECIFIED'),
(1, 'OPTION_PAYMENT_TYPE_PREMIUM'),
(2, 'OPTION_PAYMENT_TYPE_MARGINAL');


CREATE TABLE IF NOT EXISTS "tin"."option_settlement_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "option_settlement_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "option_settlement_type_id_idx" ON "tin"."option_settlement_type" USING btree ("id");
COMMENT ON TABLE "tin"."option_settlement_type" IS 'Тип опциона по способу исполнения.';
COMMENT ON COLUMN "tin"."option_settlement_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."option_settlement_type"."name" IS 'Наименование';
INSERT INTO "option_settlement_type"(id, name) VALUES
(0, 'OPTION_EXECUTION_TYPE_UNSPECIFIED'),
(1, 'OPTION_EXECUTION_TYPE_PHYSICAL_DELIVERY'),
(2, 'OPTION_EXECUTION_TYPE_CASH_SETTLEMENT');


CREATE TABLE IF NOT EXISTS "tin"."option_style" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "option_style_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "option_style_id_idx" ON "tin"."option_style" USING btree ("id");
COMMENT ON TABLE "tin"."option_style" IS 'Тип опциона по стилю.';
COMMENT ON COLUMN "tin"."option_style"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."option_style"."name" IS 'Наименование';
INSERT INTO "option_style"(id, name) VALUES
(0, 'OPTION_STYLE_UNSPECIFIED'),
(1, 'OPTION_STYLE_AMERICAN'),
(2, 'OPTION_STYLE_EUROPEAN');


CREATE TABLE IF NOT EXISTS "tin"."order_direction" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "order_direction_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "order_direction_id_idx" ON "tin"."order_direction" USING btree ("id");
COMMENT ON TABLE "tin"."order_direction" IS 'Направление операции.';
COMMENT ON COLUMN "tin"."order_direction"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."order_direction"."name" IS 'Наименование';
INSERT INTO "order_direction"(id, name) VALUES
(0, 'ORDER_DIRECTION_UNSPECIFIED'),
(1, 'ORDER_DIRECTION_BUY'),
(2, 'ORDER_DIRECTION_SELL');


CREATE TABLE IF NOT EXISTS "tin"."order_execution_report_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "order_execution_report_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "order_execution_report_status_id_idx" ON "tin"."order_execution_report_status" USING btree ("id");
COMMENT ON TABLE "tin"."order_execution_report_status" IS 'Текущий статус заявки (поручения)';
COMMENT ON COLUMN "tin"."order_execution_report_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."order_execution_report_status"."name" IS 'Наименование';
INSERT INTO "order_execution_report_status"(id, name) VALUES
(0, 'EXECUTION_REPORT_STATUS_UNSPECIFIED'),
(1, 'EXECUTION_REPORT_STATUS_FILL'),
(2, 'EXECUTION_REPORT_STATUS_REJECTED'),
(3, 'EXECUTION_REPORT_STATUS_CANCELLED'),
(4, 'EXECUTION_REPORT_STATUS_NEW'),
(5, 'EXECUTION_REPORT_STATUS_PARTIALLYFILL');


CREATE TABLE IF NOT EXISTS "tin"."order_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "order_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "order_type_id_idx" ON "tin"."order_type" USING btree ("id");
COMMENT ON TABLE "tin"."order_type" IS 'Тип заявки.';
COMMENT ON COLUMN "tin"."order_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."order_type"."name" IS 'Наименование';
INSERT INTO "order_type"(id, name) VALUES
(0, 'ORDER_TYPE_UNSPECIFIED'),
(1, 'ORDER_TYPE_LIMIT'),
(2, 'ORDER_TYPE_MARKET'),
(3, 'ORDER_TYPE_BESTPRICE');


CREATE TABLE IF NOT EXISTS "tin"."portfolio_subscription_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "portfolio_subscription_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "portfolio_subscription_status_id_idx" ON "tin"."portfolio_subscription_status" USING btree ("id");
COMMENT ON TABLE "tin"."portfolio_subscription_status" IS 'Результат подписки.';
COMMENT ON COLUMN "tin"."portfolio_subscription_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."portfolio_subscription_status"."name" IS 'Наименование';
INSERT INTO "portfolio_subscription_status"(id, name) VALUES
(0, 'PORTFOLIO_SUBSCRIPTION_STATUS_UNSPECIFIED'),
(1, 'PORTFOLIO_SUBSCRIPTION_STATUS_SUCCESS'),
(2, 'PORTFOLIO_SUBSCRIPTION_STATUS_ACCOUNT_NOT_FOUND'),
(3, 'PORTFOLIO_SUBSCRIPTION_STATUS_INTERNAL_ERROR');


CREATE TABLE IF NOT EXISTS "tin"."positions_account_subscription_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "positions_account_subscription_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "positions_account_subscription_status_id_idx" ON "tin"."positions_account_subscription_status" USING btree ("id");
COMMENT ON TABLE "tin"."positions_account_subscription_status" IS 'Результат подписки.';
COMMENT ON COLUMN "tin"."positions_account_subscription_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."positions_account_subscription_status"."name" IS 'Наименование';
INSERT INTO "positions_account_subscription_status"(id, name) VALUES
(0, 'POSITIONS_SUBSCRIPTION_STATUS_UNSPECIFIED'),
(1, 'POSITIONS_SUBSCRIPTION_STATUS_SUCCESS'),
(2, 'POSITIONS_SUBSCRIPTION_STATUS_ACCOUNT_NOT_FOUND'),
(3, 'POSITIONS_SUBSCRIPTION_STATUS_INTERNAL_ERROR');


CREATE TABLE IF NOT EXISTS "tin"."price_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "price_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "price_type_id_idx" ON "tin"."price_type" USING btree ("id");
COMMENT ON TABLE "tin"."price_type" IS 'Тип цены.';
COMMENT ON COLUMN "tin"."price_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."price_type"."name" IS 'Наименование';
INSERT INTO "price_type"(id, name) VALUES
(0, 'PRICE_TYPE_UNSPECIFIED'),
(1, 'PRICE_TYPE_POINT'),
(2, 'PRICE_TYPE_CURRENCY');


CREATE TABLE IF NOT EXISTS "tin"."real_exchange" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "real_exchange_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "real_exchange_id_idx" ON "tin"."real_exchange" USING btree ("id");
COMMENT ON TABLE "tin"."real_exchange" IS 'Реальная площадка исполнения расчётов.';
COMMENT ON COLUMN "tin"."real_exchange"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."real_exchange"."name" IS 'Наименование';
INSERT INTO "real_exchange"(id, name) VALUES
(0, 'REAL_EXCHANGE_UNSPECIFIED'),
(1, 'REAL_EXCHANGE_MOEX'),
(2, 'REAL_EXCHANGE_RTS'),
(3, 'REAL_EXCHANGE_OTC');


CREATE TABLE IF NOT EXISTS "tin"."risk_level" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "risk_level_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "risk_level_id_idx" ON "tin"."risk_level" USING btree ("id");
COMMENT ON TABLE "tin"."risk_level" IS 'Уровень риска облигации.';
COMMENT ON COLUMN "tin"."risk_level"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."risk_level"."name" IS 'Наименование';
INSERT INTO "risk_level"(id, name) VALUES
(0, 'RISK_LEVEL_UNSPECIFIED'),
(1, 'RISK_LEVEL_LOW'),
(2, 'RISK_LEVEL_MODERATE'),
(3, 'RISK_LEVEL_HIGH');


CREATE TABLE IF NOT EXISTS "tin"."security_trading_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "security_trading_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "security_trading_status_id_idx" ON "tin"."security_trading_status" USING btree ("id");
COMMENT ON TABLE "tin"."security_trading_status" IS 'Режим торгов инструмента';
COMMENT ON COLUMN "tin"."security_trading_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."security_trading_status"."name" IS 'Наименование';
INSERT INTO "security_trading_status"(id, name) VALUES
(0, 'SECURITY_TRADING_STATUS_UNSPECIFIED'),
(1, 'SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING'),
(2, 'SECURITY_TRADING_STATUS_OPENING_PERIOD'),
(3, 'SECURITY_TRADING_STATUS_CLOSING_PERIOD'),
(4, 'SECURITY_TRADING_STATUS_BREAK_IN_TRADING'),
(5, 'SECURITY_TRADING_STATUS_NORMAL_TRADING'),
(6, 'SECURITY_TRADING_STATUS_CLOSING_AUCTION'),
(7, 'SECURITY_TRADING_STATUS_DARK_POOL_AUCTION'),
(8, 'SECURITY_TRADING_STATUS_DISCRETE_AUCTION'),
(9, 'SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD'),
(10, 'SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE'),
(11, 'SECURITY_TRADING_STATUS_SESSION_ASSIGNED'),
(12, 'SECURITY_TRADING_STATUS_SESSION_CLOSE'),
(13, 'SECURITY_TRADING_STATUS_SESSION_OPEN'),
(14, 'SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING'),
(15, 'SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING'),
(16, 'SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING');


CREATE TABLE IF NOT EXISTS "tin"."share_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "share_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "share_type_id_idx" ON "tin"."share_type" USING btree ("id");
COMMENT ON TABLE "tin"."share_type" IS 'Тип акций.';
COMMENT ON COLUMN "tin"."share_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."share_type"."name" IS 'Наименование';
INSERT INTO "share_type"(id, name) VALUES
(0, 'SHARE_TYPE_UNSPECIFIED'),
(1, 'SHARE_TYPE_COMMON'),
(2, 'SHARE_TYPE_PREFERRED'),
(3, 'SHARE_TYPE_ADR'),
(4, 'SHARE_TYPE_GDR'),
(5, 'SHARE_TYPE_MLP'),
(6, 'SHARE_TYPE_NY_REG_SHRS'),
(7, 'SHARE_TYPE_CLOSED_END_FUND'),
(8, 'SHARE_TYPE_REIT');


CREATE TABLE IF NOT EXISTS "tin"."stop_order_direction" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "stop_order_direction_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stop_order_direction_id_idx" ON "tin"."stop_order_direction" USING btree ("id");
COMMENT ON TABLE "tin"."stop_order_direction" IS 'Направление сделки стоп-заявки.';
COMMENT ON COLUMN "tin"."stop_order_direction"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."stop_order_direction"."name" IS 'Наименование';
INSERT INTO "stop_order_direction"(id, name) VALUES
(0, 'STOP_ORDER_DIRECTION_UNSPECIFIED'),
(1, 'STOP_ORDER_DIRECTION_BUY'),
(2, 'STOP_ORDER_DIRECTION_SELL');


CREATE TABLE IF NOT EXISTS "tin"."stop_order_expiration_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "stop_order_expiration_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stop_order_expiration_type_id_idx" ON "tin"."stop_order_expiration_type" USING btree ("id");
COMMENT ON TABLE "tin"."stop_order_expiration_type" IS 'Тип экспирации стоп-заявке.';
COMMENT ON COLUMN "tin"."stop_order_expiration_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."stop_order_expiration_type"."name" IS 'Наименование';
INSERT INTO "stop_order_expiration_type"(id, name) VALUES
(0, 'STOP_ORDER_EXPIRATION_TYPE_UNSPECIFIED'),
(1, 'STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_CANCEL'),
(2, 'STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_DATE');


CREATE TABLE IF NOT EXISTS "tin"."stop_order_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "stop_order_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "stop_order_type_id_idx" ON "tin"."stop_order_type" USING btree ("id");
COMMENT ON TABLE "tin"."stop_order_type" IS 'Тип стоп-заявки.';
COMMENT ON COLUMN "tin"."stop_order_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."stop_order_type"."name" IS 'Наименование';
INSERT INTO "stop_order_type"(id, name) VALUES
(0, 'STOP_ORDER_TYPE_UNSPECIFIED'),
(1, 'STOP_ORDER_TYPE_TAKE_PROFIT'),
(2, 'STOP_ORDER_TYPE_STOP_LOSS'),
(3, 'STOP_ORDER_TYPE_STOP_LIMIT');


CREATE TABLE IF NOT EXISTS "tin"."structured_product_type" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "structured_product_type_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "structured_product_type_id_idx" ON "tin"."structured_product_type" USING btree ("id");
COMMENT ON TABLE "tin"."structured_product_type" IS 'Тип структурной ноты.';
COMMENT ON COLUMN "tin"."structured_product_type"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."structured_product_type"."name" IS 'Наименование';
INSERT INTO "structured_product_type"(id, name) VALUES
(0, 'SP_TYPE_UNSPECIFIED'),
(1, 'SP_TYPE_DELIVERABLE'),
(2, 'SP_TYPE_NON_DELIVERABLE');


CREATE TABLE IF NOT EXISTS "tin"."subscription_action" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "subscription_action_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "subscription_action_id_idx" ON "tin"."subscription_action" USING btree ("id");
COMMENT ON TABLE "tin"."subscription_action" IS 'Тип операции со списком подписок.';
COMMENT ON COLUMN "tin"."subscription_action"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."subscription_action"."name" IS 'Наименование';
INSERT INTO "subscription_action"(id, name) VALUES
(0, 'SUBSCRIPTION_ACTION_UNSPECIFIED'),
(1, 'SUBSCRIPTION_ACTION_SUBSCRIBE'),
(2, 'SUBSCRIPTION_ACTION_UNSUBSCRIBE');


CREATE TABLE IF NOT EXISTS "tin"."subscription_interval" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "subscription_interval_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "subscription_interval_id_idx" ON "tin"."subscription_interval" USING btree ("id");
COMMENT ON TABLE "tin"."subscription_interval" IS 'Интервал свечи.';
COMMENT ON COLUMN "tin"."subscription_interval"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."subscription_interval"."name" IS 'Наименование';
INSERT INTO "subscription_interval"(id, name) VALUES
(0, 'SUBSCRIPTION_INTERVAL_UNSPECIFIED'),
(1, 'SUBSCRIPTION_INTERVAL_ONE_MINUTE'),
(2, 'SUBSCRIPTION_INTERVAL_FIVE_MINUTES');


CREATE TABLE IF NOT EXISTS "tin"."subscription_status" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "subscription_status_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "subscription_status_id_idx" ON "tin"."subscription_status" USING btree ("id");
COMMENT ON TABLE "tin"."subscription_status" IS 'Результат подписки.';
COMMENT ON COLUMN "tin"."subscription_status"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."subscription_status"."name" IS 'Наименование';
INSERT INTO "subscription_status"(id, name) VALUES
(0, 'SUBSCRIPTION_STATUS_UNSPECIFIED'),
(1, 'SUBSCRIPTION_STATUS_SUCCESS'),
(2, 'SUBSCRIPTION_STATUS_INSTRUMENT_NOT_FOUND'),
(3, 'SUBSCRIPTION_STATUS_SUBSCRIPTION_ACTION_IS_INVALID'),
(4, 'SUBSCRIPTION_STATUS_DEPTH_IS_INVALID'),
(5, 'SUBSCRIPTION_STATUS_INTERVAL_IS_INVALID'),
(6, 'SUBSCRIPTION_STATUS_LIMIT_IS_EXCEEDED'),
(7, 'SUBSCRIPTION_STATUS_INTERNAL_ERROR'),
(8, 'SUBSCRIPTION_STATUS_TOO_MANY_REQUESTS');


CREATE TABLE IF NOT EXISTS "tin"."trade_direction" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "trade_direction_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "trade_direction_id_idx" ON "tin"."trade_direction" USING btree ("id");
COMMENT ON TABLE "tin"."trade_direction" IS 'Направление сделки.';
COMMENT ON COLUMN "tin"."trade_direction"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."trade_direction"."name" IS 'Наименование';
INSERT INTO "trade_direction"(id, name) VALUES
(0, 'TRADE_DIRECTION_UNSPECIFIED'),
(1, 'TRADE_DIRECTION_BUY'),
(2, 'TRADE_DIRECTION_SELL');


CREATE TABLE IF NOT EXISTS "tin"."account" (
	"id" text NOT NULL,
	"type_id" bigint NULL,
	"name" text NOT NULL,
	"status_id" bigint NULL,
	"opened_date" timestamptz NULL,
	"closed_date" timestamptz NULL,
	"access_level_id" bigint NULL,
	CONSTRAINT "account_pk" PRIMARY KEY ("id"),
	CONSTRAINT "account_type_id_fk" FOREIGN KEY ("type_id") REFERENCES "tin"."account_type" ("id"),
	CONSTRAINT "account_status_id_fk" FOREIGN KEY ("status_id") REFERENCES "tin"."account_status" ("id"),
	CONSTRAINT "account_access_level_id_fk" FOREIGN KEY ("access_level_id") REFERENCES "tin"."access_level" ("id")
);
CREATE INDEX IF NOT EXISTS "account_type_id_idx" ON "tin"."account" USING btree ("type_id");
CREATE INDEX IF NOT EXISTS "account_status_id_idx" ON "tin"."account" USING btree ("status_id");
CREATE INDEX IF NOT EXISTS "account_access_level_id_idx" ON "tin"."account" USING btree ("access_level_id");
COMMENT ON TABLE "tin"."account" IS 'Информация о счёте.';
COMMENT ON COLUMN "tin"."account"."id" IS ' Идентификатор счёта.';
COMMENT ON COLUMN "tin"."account"."type_id" IS ' Тип счёта.';
COMMENT ON COLUMN "tin"."account"."name" IS ' Название счёта.';
COMMENT ON COLUMN "tin"."account"."status_id" IS ' Статус счёта.';
COMMENT ON COLUMN "tin"."account"."opened_date" IS ' Дата открытия счёта в часовом поясе UTC.';
COMMENT ON COLUMN "tin"."account"."closed_date" IS ' Дата закрытия счёта в часовом поясе UTC.';
COMMENT ON COLUMN "tin"."account"."access_level_id" IS ' Уровень доступа к текущему счёту (определяется токеном).';

