
CREATE TABLE IF NOT EXISTS "tin"."CurrencyRequest" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "CurrencyRequest_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "CurrencyRequest_id_idx" ON "tin"."CurrencyRequest" USING btree ("id");
COMMENT ON TABLE "tin"."CurrencyRequest" IS '';
COMMENT ON COLUMN "tin"."CurrencyRequest"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."CurrencyRequest"."name" IS 'Наименование';
INSERT INTO "CurrencyRequest"(id, name) VALUES
(0, 'RUB'),
(1, 'USD'),
(2, 'EUR');


CREATE TABLE IF NOT EXISTS "tin"."InstrumentType" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "InstrumentType_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "InstrumentType_id_idx" ON "tin"."InstrumentType" USING btree ("id");
COMMENT ON TABLE "tin"."InstrumentType" IS 'Тип инструмента.';
COMMENT ON COLUMN "tin"."InstrumentType"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."InstrumentType"."name" IS 'Наименование';
INSERT INTO "InstrumentType"(id, name) VALUES
(0, 'INSTRUMENT_TYPE_UNSPECIFIED'),
(1, 'INSTRUMENT_TYPE_BOND'),
(2, 'INSTRUMENT_TYPE_SHARE'),
(3, 'INSTRUMENT_TYPE_CURRENCY'),
(4, 'INSTRUMENT_TYPE_ETF'),
(5, 'INSTRUMENT_TYPE_FUTURES'),
(6, 'INSTRUMENT_TYPE_SP'),
(7, 'INSTRUMENT_TYPE_OPTION'),
(8, 'INSTRUMENT_TYPE_CLEARING_CERTIFICATE');


CREATE TABLE IF NOT EXISTS "tin"."OperationState" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "OperationState_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "OperationState_id_idx" ON "tin"."OperationState" USING btree ("id");
COMMENT ON TABLE "tin"."OperationState" IS 'Статус запрашиваемых операций.';
COMMENT ON COLUMN "tin"."OperationState"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."OperationState"."name" IS 'Наименование';
INSERT INTO "OperationState"(id, name) VALUES
(0, 'OPERATION_STATE_UNSPECIFIED'),
(1, 'OPERATION_STATE_EXECUTED'),
(2, 'OPERATION_STATE_CANCELED'),
(3, 'OPERATION_STATE_PROGRESS');


CREATE TABLE IF NOT EXISTS "tin"."OperationType" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "OperationType_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "OperationType_id_idx" ON "tin"."OperationType" USING btree ("id");
COMMENT ON TABLE "tin"."OperationType" IS 'Тип операции.';
COMMENT ON COLUMN "tin"."OperationType"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."OperationType"."name" IS 'Наименование';
INSERT INTO "OperationType"(id, name) VALUES
(0, 'OPERATION_TYPE_UNSPECIFIED'),
(1, 'OPERATION_TYPE_INPUT'),
(2, 'OPERATION_TYPE_BOND_TAX'),
(3, 'OPERATION_TYPE_OUTPUT_SECURITIES'),
(4, 'OPERATION_TYPE_OVERNIGHT'),
(5, 'OPERATION_TYPE_TAX'),
(6, 'OPERATION_TYPE_BOND_REPAYMENT_FULL'),
(7, 'OPERATION_TYPE_SELL_CARD'),
(8, 'OPERATION_TYPE_DIVIDEND_TAX'),
(9, 'OPERATION_TYPE_OUTPUT'),
(10, 'OPERATION_TYPE_BOND_REPAYMENT'),
(11, 'OPERATION_TYPE_TAX_CORRECTION'),
(12, 'OPERATION_TYPE_SERVICE_FEE'),
(13, 'OPERATION_TYPE_BENEFIT_TAX'),
(14, 'OPERATION_TYPE_MARGIN_FEE'),
(15, 'OPERATION_TYPE_BUY'),
(16, 'OPERATION_TYPE_BUY_CARD'),
(17, 'OPERATION_TYPE_INPUT_SECURITIES'),
(18, 'OPERATION_TYPE_SELL_MARGIN'),
(19, 'OPERATION_TYPE_BROKER_FEE'),
(20, 'OPERATION_TYPE_BUY_MARGIN'),
(21, 'OPERATION_TYPE_DIVIDEND'),
(22, 'OPERATION_TYPE_SELL'),
(23, 'OPERATION_TYPE_COUPON'),
(24, 'OPERATION_TYPE_SUCCESS_FEE'),
(25, 'OPERATION_TYPE_DIVIDEND_TRANSFER'),
(26, 'OPERATION_TYPE_ACCRUING_VARMARGIN'),
(27, 'OPERATION_TYPE_WRITING_OFF_VARMARGIN'),
(28, 'OPERATION_TYPE_DELIVERY_BUY'),
(29, 'OPERATION_TYPE_DELIVERY_SELL'),
(30, 'OPERATION_TYPE_TRACK_MFEE'),
(31, 'OPERATION_TYPE_TRACK_PFEE'),
(32, 'OPERATION_TYPE_TAX_PROGRESSIVE'),
(33, 'OPERATION_TYPE_BOND_TAX_PROGRESSIVE'),
(34, 'OPERATION_TYPE_DIVIDEND_TAX_PROGRESSIVE'),
(35, 'OPERATION_TYPE_BENEFIT_TAX_PROGRESSIVE'),
(36, 'OPERATION_TYPE_TAX_CORRECTION_PROGRESSIVE'),
(37, 'OPERATION_TYPE_TAX_REPO_PROGRESSIVE'),
(38, 'OPERATION_TYPE_TAX_REPO'),
(39, 'OPERATION_TYPE_TAX_REPO_HOLD'),
(40, 'OPERATION_TYPE_TAX_REPO_REFUND'),
(41, 'OPERATION_TYPE_TAX_REPO_HOLD_PROGRESSIVE'),
(42, 'OPERATION_TYPE_TAX_REPO_REFUND_PROGRESSIVE'),
(43, 'OPERATION_TYPE_DIV_EXT'),
(44, 'OPERATION_TYPE_TAX_CORRECTION_COUPON'),
(45, 'OPERATION_TYPE_CASH_FEE'),
(46, 'OPERATION_TYPE_OUT_FEE'),
(47, 'OPERATION_TYPE_OUT_STAMP_DUTY'),
(50, 'OPERATION_TYPE_OUTPUT_SWIFT'),
(51, 'OPERATION_TYPE_INPUT_SWIFT'),
(53, 'OPERATION_TYPE_OUTPUT_ACQUIRING'),
(54, 'OPERATION_TYPE_INPUT_ACQUIRING'),
(55, 'OPERATION_TYPE_OUTPUT_PENALTY'),
(56, 'OPERATION_TYPE_ADVICE_FEE'),
(57, 'OPERATION_TYPE_TRANS_IIS_BS'),
(58, 'OPERATION_TYPE_TRANS_BS_BS'),
(59, 'OPERATION_TYPE_OUT_MULTI'),
(60, 'OPERATION_TYPE_INP_MULTI'),
(61, 'OPERATION_TYPE_OVER_PLACEMENT'),
(62, 'OPERATION_TYPE_OVER_COM'),
(63, 'OPERATION_TYPE_OVER_INCOME'),
(64, 'OPERATION_TYPE_OPTION_EXPIRATION');


CREATE TABLE IF NOT EXISTS "tin"."PortfolioSubscriptionStatus" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "PortfolioSubscriptionStatus_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "PortfolioSubscriptionStatus_id_idx" ON "tin"."PortfolioSubscriptionStatus" USING btree ("id");
COMMENT ON TABLE "tin"."PortfolioSubscriptionStatus" IS 'Результат подписки.';
COMMENT ON COLUMN "tin"."PortfolioSubscriptionStatus"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."PortfolioSubscriptionStatus"."name" IS 'Наименование';
INSERT INTO "PortfolioSubscriptionStatus"(id, name) VALUES
(0, 'PORTFOLIO_SUBSCRIPTION_STATUS_UNSPECIFIED'),
(1, 'PORTFOLIO_SUBSCRIPTION_STATUS_SUCCESS'),
(2, 'PORTFOLIO_SUBSCRIPTION_STATUS_ACCOUNT_NOT_FOUND'),
(3, 'PORTFOLIO_SUBSCRIPTION_STATUS_INTERNAL_ERROR');


CREATE TABLE IF NOT EXISTS "tin"."PositionsAccountSubscriptionStatus" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "PositionsAccountSubscriptionStatus_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "PositionsAccountSubscriptionStatus_id_idx" ON "tin"."PositionsAccountSubscriptionStatus" USING btree ("id");
COMMENT ON TABLE "tin"."PositionsAccountSubscriptionStatus" IS 'Результат подписки.';
COMMENT ON COLUMN "tin"."PositionsAccountSubscriptionStatus"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."PositionsAccountSubscriptionStatus"."name" IS 'Наименование';
INSERT INTO "PositionsAccountSubscriptionStatus"(id, name) VALUES
(0, 'POSITIONS_SUBSCRIPTION_STATUS_UNSPECIFIED'),
(1, 'POSITIONS_SUBSCRIPTION_STATUS_SUCCESS'),
(2, 'POSITIONS_SUBSCRIPTION_STATUS_ACCOUNT_NOT_FOUND'),
(3, 'POSITIONS_SUBSCRIPTION_STATUS_INTERNAL_ERROR');


CREATE TABLE IF NOT EXISTS "tin"."SecurityTradingStatus" (
	"id" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "SecurityTradingStatus_pk" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "SecurityTradingStatus_id_idx" ON "tin"."SecurityTradingStatus" USING btree ("id");
COMMENT ON TABLE "tin"."SecurityTradingStatus" IS 'Режим торгов инструмента';
COMMENT ON COLUMN "tin"."SecurityTradingStatus"."id" IS 'Уникальный технический идентификатор';
COMMENT ON COLUMN "tin"."SecurityTradingStatus"."name" IS 'Наименование';
INSERT INTO "SecurityTradingStatus"(id, name) VALUES
(0, 'SECURITY_TRADING_STATUS_UNSPECIFIED'),
(1, 'SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING'),
(2, 'SECURITY_TRADING_STATUS_OPENING_PERIOD'),
(3, 'SECURITY_TRADING_STATUS_CLOSING_PERIOD'),
(4, 'SECURITY_TRADING_STATUS_BREAK_IN_TRADING'),
(5, 'SECURITY_TRADING_STATUS_NORMAL_TRADING'),
(6, 'SECURITY_TRADING_STATUS_CLOSING_AUCTION'),
(7, 'SECURITY_TRADING_STATUS_DARK_POOL_AUCTION'),
(8, 'SECURITY_TRADING_STATUS_DISCRETE_AUCTION'),
(9, 'SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD'),
(10, 'SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE'),
(11, 'SECURITY_TRADING_STATUS_SESSION_ASSIGNED'),
(12, 'SECURITY_TRADING_STATUS_SESSION_CLOSE'),
(13, 'SECURITY_TRADING_STATUS_SESSION_OPEN'),
(14, 'SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING'),
(15, 'SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING'),
(16, 'SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING');


CREATE TABLE IF NOT EXISTS "tin"."BrokerReport" (
	"trade_id" text NOT NULL,
	"order_id" text NOT NULL,
	"figi" text NOT NULL,
	"execute_sign" text NOT NULL,
	"trade_datetime" timestamptz NULL,
	"exchange" text NOT NULL,
	"class_code" text NOT NULL,
	"direction" text NOT NULL,
	"name" text NOT NULL,
	"ticker" text NOT NULL,
	"price_currency" text NULL,
	"price_units" bigint NULL,
	"price_nano" integer NULL,
	"quantity" bigint NOT NULL,
	"order_amount_currency" text NULL,
	"order_amount_units" bigint NULL,
	"order_amount_nano" integer NULL,
	"aci_value_units" bigint NULL,
	"aci_value_nano" integer NULL,
	"total_order_amount_currency" text NULL,
	"total_order_amount_units" bigint NULL,
	"total_order_amount_nano" integer NULL,
	"broker_commission_currency" text NULL,
	"broker_commission_units" bigint NULL,
	"broker_commission_nano" integer NULL,
	"exchange_commission_currency" text NULL,
	"exchange_commission_units" bigint NULL,
	"exchange_commission_nano" integer NULL,
	"exchange_clearing_commission_currency" text NULL,
	"exchange_clearing_commission_units" bigint NULL,
	"exchange_clearing_commission_nano" integer NULL,
	"repo_rate_units" bigint NULL,
	"repo_rate_nano" integer NULL,
	"party" text NOT NULL,
	"clear_value_date" timestamptz NULL,
	"sec_value_date" timestamptz NULL,
	"broker_status" text NOT NULL,
	"separate_agreement_type" text NOT NULL,
	"separate_agreement_number" text NOT NULL,
	"separate_agreement_date" text NOT NULL,
	"delivery_type" text NOT NULL,
	CONSTRAINT "BrokerReport_pk" PRIMARY KEY ("trade_id")
);
COMMENT ON TABLE "tin"."BrokerReport" IS '';
COMMENT ON COLUMN "tin"."BrokerReport"."trade_id" IS 'Номер сделки.';
COMMENT ON COLUMN "tin"."BrokerReport"."order_id" IS 'Номер поручения.';
COMMENT ON COLUMN "tin"."BrokerReport"."figi" IS 'Figi-идентификатор инструмента.';
COMMENT ON COLUMN "tin"."BrokerReport"."execute_sign" IS 'Признак исполнения.';
COMMENT ON COLUMN "tin"."BrokerReport"."trade_datetime" IS 'Дата и время заключения в часовом поясе UTC.';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange" IS 'Торговая площадка.';
COMMENT ON COLUMN "tin"."BrokerReport"."class_code" IS 'Режим торгов.';
COMMENT ON COLUMN "tin"."BrokerReport"."direction" IS 'Вид сделки.';
COMMENT ON COLUMN "tin"."BrokerReport"."name" IS 'Сокращённое наименование актива.';
COMMENT ON COLUMN "tin"."BrokerReport"."ticker" IS 'Код актива.';
COMMENT ON COLUMN "tin"."BrokerReport"."price_currency" IS 'Цена за единицу. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."BrokerReport"."price_units" IS 'Цена за единицу. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."price_nano" IS 'Цена за единицу. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."quantity" IS 'Количество.';
COMMENT ON COLUMN "tin"."BrokerReport"."order_amount_currency" IS 'Сумма (без НКД). /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."BrokerReport"."order_amount_units" IS 'Сумма (без НКД). /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."order_amount_nano" IS 'Сумма (без НКД). /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."aci_value_units" IS 'НКД. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."aci_value_nano" IS 'НКД. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."total_order_amount_currency" IS 'Сумма сделки. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."BrokerReport"."total_order_amount_units" IS 'Сумма сделки. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."total_order_amount_nano" IS 'Сумма сделки. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."broker_commission_currency" IS 'Комиссия брокера. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."BrokerReport"."broker_commission_units" IS 'Комиссия брокера. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."broker_commission_nano" IS 'Комиссия брокера. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange_commission_currency" IS 'Комиссия биржи. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange_commission_units" IS 'Комиссия биржи. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange_commission_nano" IS 'Комиссия биржи. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange_clearing_commission_currency" IS 'Комиссия клир. центра. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange_clearing_commission_units" IS 'Комиссия клир. центра. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."exchange_clearing_commission_nano" IS 'Комиссия клир. центра. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."repo_rate_units" IS 'Ставка РЕПО (%). /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."repo_rate_nano" IS 'Ставка РЕПО (%). /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."BrokerReport"."party" IS 'Контрагент/Брокер.';
COMMENT ON COLUMN "tin"."BrokerReport"."clear_value_date" IS 'Дата расчётов в часовом поясе UTC.';
COMMENT ON COLUMN "tin"."BrokerReport"."sec_value_date" IS 'Дата поставки в часовом поясе UTC.';
COMMENT ON COLUMN "tin"."BrokerReport"."broker_status" IS 'Статус брокера.';
COMMENT ON COLUMN "tin"."BrokerReport"."separate_agreement_type" IS 'Тип дог.';
COMMENT ON COLUMN "tin"."BrokerReport"."separate_agreement_number" IS 'Номер дог.';
COMMENT ON COLUMN "tin"."BrokerReport"."separate_agreement_date" IS 'Дата дог.';
COMMENT ON COLUMN "tin"."BrokerReport"."delivery_type" IS 'Тип расчёта по сделке.';

CREATE TABLE IF NOT EXISTS "tin"."OperationTrade" (
	"trade_id" text NOT NULL,
	"date_time" timestamptz NULL,
	"quantity" bigint NOT NULL,
	"price_currency" text NULL,
	"price_units" bigint NULL,
	"price_nano" integer NULL,
	CONSTRAINT "OperationTrade_pk" PRIMARY KEY ("trade_id")
);
COMMENT ON TABLE "tin"."OperationTrade" IS 'Сделка по операции.';
COMMENT ON COLUMN "tin"."OperationTrade"."trade_id" IS 'Идентификатор сделки.';
COMMENT ON COLUMN "tin"."OperationTrade"."date_time" IS 'Дата и время сделки в часовом поясе UTC.';
COMMENT ON COLUMN "tin"."OperationTrade"."quantity" IS 'Количество инструментов.';
COMMENT ON COLUMN "tin"."OperationTrade"."price_currency" IS 'Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."OperationTrade"."price_units" IS 'Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."OperationTrade"."price_nano" IS 'Цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  дробная часть суммы, может быть отрицательным числом';

CREATE TABLE IF NOT EXISTS "tin"."PortfolioPosition" (
	"figi" text NOT NULL,
	"instrument_type" text NOT NULL,
	"quantity_units" bigint NULL,
	"quantity_nano" integer NULL,
	"average_position_price_currency" text NULL,
	"average_position_price_units" bigint NULL,
	"average_position_price_nano" integer NULL,
	"expected_yield_units" bigint NULL,
	"expected_yield_nano" integer NULL,
	"current_nkd_currency" text NULL,
	"current_nkd_units" bigint NULL,
	"current_nkd_nano" integer NULL,
	"average_position_price_pt_units" bigint NULL,
	"average_position_price_pt_nano" integer NULL,
	"current_price_currency" text NULL,
	"current_price_units" bigint NULL,
	"current_price_nano" integer NULL,
	"average_position_price_fifo_currency" text NULL,
	"average_position_price_fifo_units" bigint NULL,
	"average_position_price_fifo_nano" integer NULL,
	"quantity_lots_units" bigint NULL,
	"quantity_lots_nano" integer NULL,
	"blocked" bool NOT NULL,
	"blocked_lots_units" bigint NULL,
	"blocked_lots_nano" integer NULL,
	"position_uid" text NOT NULL,
	"instrument_uid" text NOT NULL,
	"var_margin_currency" text NULL,
	"var_margin_units" bigint NULL,
	"var_margin_nano" integer NULL,
	"expected_yield_fifo_units" bigint NULL,
	"expected_yield_fifo_nano" integer NULL,
	CONSTRAINT "PortfolioPosition_pk" PRIMARY KEY ("figi")
);
COMMENT ON TABLE "tin"."PortfolioPosition" IS 'Позиции портфеля.';
COMMENT ON COLUMN "tin"."PortfolioPosition"."figi" IS 'Figi-идентификатора инструмента.';
COMMENT ON COLUMN "tin"."PortfolioPosition"."instrument_type" IS 'Тип инструмента.';
COMMENT ON COLUMN "tin"."PortfolioPosition"."quantity_units" IS 'Количество инструмента в портфеле в штуках. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."quantity_nano" IS 'Количество инструмента в портфеле в штуках. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_currency" IS 'Средневзвешенная цена позиции. **Возможна задержка до секунды для пересчёта**. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_units" IS 'Средневзвешенная цена позиции. **Возможна задержка до секунды для пересчёта**. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_nano" IS 'Средневзвешенная цена позиции. **Возможна задержка до секунды для пересчёта**. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."expected_yield_units" IS 'Текущая рассчитанная доходность позиции. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."expected_yield_nano" IS 'Текущая рассчитанная доходность позиции. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."current_nkd_currency" IS ' Текущий НКД. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."PortfolioPosition"."current_nkd_units" IS ' Текущий НКД. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."current_nkd_nano" IS ' Текущий НКД. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_pt_units" IS ' Deprecated Средняя цена позиции в пунктах (для фьючерсов). **Возможна задержка до секунды для пересчёта**. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_pt_nano" IS ' Deprecated Средняя цена позиции в пунктах (для фьючерсов). **Возможна задержка до секунды для пересчёта**. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."current_price_currency" IS 'Текущая цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."PortfolioPosition"."current_price_units" IS 'Текущая цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."current_price_nano" IS 'Текущая цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_fifo_currency" IS 'Средняя цена позиции по методу FIFO. **Возможна задержка до секунды для пересчёта**. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_fifo_units" IS 'Средняя цена позиции по методу FIFO. **Возможна задержка до секунды для пересчёта**. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."average_position_price_fifo_nano" IS 'Средняя цена позиции по методу FIFO. **Возможна задержка до секунды для пересчёта**. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."quantity_lots_units" IS 'Deprecated Количество лотов в портфеле. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."quantity_lots_nano" IS 'Deprecated Количество лотов в портфеле. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."blocked" IS 'Заблокировано на бирже.';
COMMENT ON COLUMN "tin"."PortfolioPosition"."blocked_lots_units" IS 'Количество бумаг, заблокированных выставленными заявками. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."blocked_lots_nano" IS 'Количество бумаг, заблокированных выставленными заявками. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."position_uid" IS 'position_uid-идентификатора инструмента';
COMMENT ON COLUMN "tin"."PortfolioPosition"."instrument_uid" IS 'instrument_uid-идентификатора инструмента';
COMMENT ON COLUMN "tin"."PortfolioPosition"."var_margin_currency" IS 'Вариационная маржа /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."PortfolioPosition"."var_margin_units" IS 'Вариационная маржа /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."var_margin_nano" IS 'Вариационная маржа /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."expected_yield_fifo_units" IS 'Текущая рассчитанная доходность позиции. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."PortfolioPosition"."expected_yield_fifo_nano" IS 'Текущая рассчитанная доходность позиции. /  дробная часть суммы, может быть отрицательным числом';

CREATE TABLE IF NOT EXISTS "tin"."PositionsFutures" (
	"figi" text NOT NULL,
	"blocked" bigint NOT NULL,
	"balance" bigint NOT NULL,
	"position_uid" text NOT NULL,
	"instrument_uid" text NOT NULL,
	CONSTRAINT "PositionsFutures_pk" PRIMARY KEY ("figi")
);
COMMENT ON TABLE "tin"."PositionsFutures" IS 'Баланс фьючерса.';
COMMENT ON COLUMN "tin"."PositionsFutures"."figi" IS 'Figi-идентификатор фьючерса.';
COMMENT ON COLUMN "tin"."PositionsFutures"."blocked" IS 'Количество бумаг заблокированных выставленными заявками.';
COMMENT ON COLUMN "tin"."PositionsFutures"."balance" IS 'Текущий незаблокированный баланс.';
COMMENT ON COLUMN "tin"."PositionsFutures"."position_uid" IS 'Уникальный идентификатор позиции.';
COMMENT ON COLUMN "tin"."PositionsFutures"."instrument_uid" IS 'Уникальный идентификатор  инструмента.';

CREATE TABLE IF NOT EXISTS "tin"."PositionsSecurities" (
	"figi" text NOT NULL,
	"blocked" bigint NOT NULL,
	"balance" bigint NOT NULL,
	"position_uid" text NOT NULL,
	"instrument_uid" text NOT NULL,
	"exchange_blocked" bool NOT NULL,
	"instrument_type" text NOT NULL,
	CONSTRAINT "PositionsSecurities_pk" PRIMARY KEY ("figi")
);
COMMENT ON TABLE "tin"."PositionsSecurities" IS 'Баланс позиции ценной бумаги.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."figi" IS 'Figi-идентификатор бумаги.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."blocked" IS 'Количество бумаг заблокированных выставленными заявками.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."balance" IS 'Текущий незаблокированный баланс.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."position_uid" IS 'Уникальный идентификатор позиции.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."instrument_uid" IS 'Уникальный идентификатор  инструмента.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."exchange_blocked" IS 'Заблокировано на бирже.';
COMMENT ON COLUMN "tin"."PositionsSecurities"."instrument_type" IS 'Тип инструмента.';

CREATE TABLE IF NOT EXISTS "tin"."VirtualPortfolioPosition" (
	"position_uid" text NOT NULL,
	"instrument_uid" text NOT NULL,
	"figi" text NOT NULL,
	"instrument_type" text NOT NULL,
	"quantity_units" bigint NULL,
	"quantity_nano" integer NULL,
	"average_position_price_currency" text NULL,
	"average_position_price_units" bigint NULL,
	"average_position_price_nano" integer NULL,
	"expected_yield_units" bigint NULL,
	"expected_yield_nano" integer NULL,
	"expected_yield_fifo_units" bigint NULL,
	"expected_yield_fifo_nano" integer NULL,
	"expire_date" timestamptz NULL,
	"current_price_currency" text NULL,
	"current_price_units" bigint NULL,
	"current_price_nano" integer NULL,
	"average_position_price_fifo_currency" text NULL,
	"average_position_price_fifo_units" bigint NULL,
	"average_position_price_fifo_nano" integer NULL,
	CONSTRAINT "VirtualPortfolioPosition_pk" PRIMARY KEY ("figi")
);
COMMENT ON TABLE "tin"."VirtualPortfolioPosition" IS '';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."position_uid" IS 'position_uid-идентификатора инструмента';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."instrument_uid" IS 'instrument_uid-идентификатора инструмента';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."figi" IS 'Figi-идентификатора инструмента.';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."instrument_type" IS 'Тип инструмента.';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."quantity_units" IS 'Количество инструмента в портфеле в штуках. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."quantity_nano" IS 'Количество инструмента в портфеле в штуках. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."average_position_price_currency" IS 'Средневзвешенная цена позиции. **Возможна задержка до секунды для пересчёта**. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."average_position_price_units" IS 'Средневзвешенная цена позиции. **Возможна задержка до секунды для пересчёта**. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."average_position_price_nano" IS 'Средневзвешенная цена позиции. **Возможна задержка до секунды для пересчёта**. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."expected_yield_units" IS 'Текущая рассчитанная доходность позиции. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."expected_yield_nano" IS 'Текущая рассчитанная доходность позиции. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."expected_yield_fifo_units" IS 'Текущая рассчитанная доходность позиции. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."expected_yield_fifo_nano" IS 'Текущая рассчитанная доходность позиции. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."expire_date" IS 'Дата до которой нужно продать виртуальные бумаги, после этой даты виртуальная позиция "сгорит"';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."current_price_currency" IS 'Текущая цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."current_price_units" IS 'Текущая цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."current_price_nano" IS 'Текущая цена за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."average_position_price_fifo_currency" IS 'Средняя цена позиции по методу FIFO. **Возможна задержка до секунды для пересчёта**. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."average_position_price_fifo_units" IS 'Средняя цена позиции по методу FIFO. **Возможна задержка до секунды для пересчёта**. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."VirtualPortfolioPosition"."average_position_price_fifo_nano" IS 'Средняя цена позиции по методу FIFO. **Возможна задержка до секунды для пересчёта**. /  дробная часть суммы, может быть отрицательным числом';

CREATE TABLE IF NOT EXISTS "tin"."OperationsRequest" (
	"account_id" text NOT NULL,
	"from" timestamptz NULL,
	"to" timestamptz NULL,
	"state_id" bigint NULL,
	"figi" text NOT NULL,
	CONSTRAINT "OperationsRequest_pk" PRIMARY KEY ("figi"),
	CONSTRAINT "OperationsRequest_state_id_fk" FOREIGN KEY ("state_id") REFERENCES "tin"."OperationState" ("id")
);
CREATE INDEX IF NOT EXISTS "OperationsRequest_state_id_idx" ON "tin"."OperationsRequest" USING btree ("state_id");
COMMENT ON TABLE "tin"."OperationsRequest" IS 'Запрос получения списка операций по счёту.';
COMMENT ON COLUMN "tin"."OperationsRequest"."account_id" IS 'Идентификатор счёта клиента.';
COMMENT ON COLUMN "tin"."OperationsRequest"."from" IS 'Начало периода (по UTC).';
COMMENT ON COLUMN "tin"."OperationsRequest"."to" IS 'Окончание периода (по UTC).';
COMMENT ON COLUMN "tin"."OperationsRequest"."state_id" IS 'Статус запрашиваемых операций.';
COMMENT ON COLUMN "tin"."OperationsRequest"."figi" IS 'Figi-идентификатор инструмента для фильтрации.';

CREATE TABLE IF NOT EXISTS "tin"."Operation" (
	"id" text NOT NULL,
	"parent_operation_id" text NOT NULL,
	"currency" text NOT NULL,
	"payment_currency" text NULL,
	"payment_units" bigint NULL,
	"payment_nano" integer NULL,
	"price_currency" text NULL,
	"price_units" bigint NULL,
	"price_nano" integer NULL,
	"state_id" bigint NULL,
	"quantity" bigint NOT NULL,
	"quantity_rest" bigint NOT NULL,
	"figi" text NOT NULL,
	"instrument_type" text NOT NULL,
	"date" timestamptz NULL,
	"type" text NOT NULL,
	"operation_type_id" bigint NULL,
	"trades_id" text NULL,
	"asset_uid" text NOT NULL,
	"position_uid" text NOT NULL,
	"instrument_uid" text NOT NULL,
	CONSTRAINT "Operation_pk" PRIMARY KEY ("id"),
	CONSTRAINT "Operation_state_id_fk" FOREIGN KEY ("state_id") REFERENCES "tin"."OperationState" ("id"),
	CONSTRAINT "Operation_operation_type_id_fk" FOREIGN KEY ("operation_type_id") REFERENCES "tin"."OperationType" ("id"),
	CONSTRAINT "Operation_trades_id_fk" FOREIGN KEY ("trades_id") REFERENCES "tin"."OperationTrade" ("trade_id")
);
CREATE INDEX IF NOT EXISTS "Operation_state_id_idx" ON "tin"."Operation" USING btree ("state_id");
CREATE INDEX IF NOT EXISTS "Operation_operation_type_id_idx" ON "tin"."Operation" USING btree ("operation_type_id");
CREATE INDEX IF NOT EXISTS "Operation_trades_id_idx" ON "tin"."Operation" USING btree ("trades_id");
COMMENT ON TABLE "tin"."Operation" IS 'Данные по операции.';
COMMENT ON COLUMN "tin"."Operation"."id" IS 'Идентификатор операции.';
COMMENT ON COLUMN "tin"."Operation"."parent_operation_id" IS 'Идентификатор родительской операции.';
COMMENT ON COLUMN "tin"."Operation"."currency" IS 'Валюта операции.';
COMMENT ON COLUMN "tin"."Operation"."payment_currency" IS 'Сумма операции. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."Operation"."payment_units" IS 'Сумма операции. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."Operation"."payment_nano" IS 'Сумма операции. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."Operation"."price_currency" IS 'Цена операции за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  строковый ISO-код валюты';
COMMENT ON COLUMN "tin"."Operation"."price_units" IS 'Цена операции за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  целая часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."Operation"."price_nano" IS 'Цена операции за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента. /  дробная часть суммы, может быть отрицательным числом';
COMMENT ON COLUMN "tin"."Operation"."state_id" IS 'Статус операции.';
COMMENT ON COLUMN "tin"."Operation"."quantity" IS 'Количество единиц инструмента.';
COMMENT ON COLUMN "tin"."Operation"."quantity_rest" IS 'Неисполненный остаток по сделке.';
COMMENT ON COLUMN "tin"."Operation"."figi" IS 'Figi-идентификатор инструмента, связанного с операцией.';
COMMENT ON COLUMN "tin"."Operation"."instrument_type" IS 'Тип инструмента. Возможные значения: </br>**bond** — облигация; </br>**share** — акция; </br>**currency** — валюта; </br>**etf** — фонд; </br>**futures** — фьючерс.';
COMMENT ON COLUMN "tin"."Operation"."date" IS 'Дата и время операции в формате часовом поясе UTC.';
COMMENT ON COLUMN "tin"."Operation"."type" IS 'Текстовое описание типа операции.';
COMMENT ON COLUMN "tin"."Operation"."operation_type_id" IS 'Тип операции.';
COMMENT ON COLUMN "tin"."Operation"."trades_id" IS 'Массив сделок.';
COMMENT ON COLUMN "tin"."Operation"."asset_uid" IS 'Идентификатор актива';
COMMENT ON COLUMN "tin"."Operation"."position_uid" IS 'position_uid-идентификатора инструмента.';
COMMENT ON COLUMN "tin"."Operation"."instrument_uid" IS 'Уникальный идентификатор инструмента.';

